### ISSUE TITLE
Github: unauthorized response code

### ISSUE THREAD

**Issue by Austinate** [angledotdev/support#4]
## Description
`Add new application flow` shows `Github returned an unathorized response code` error after re-adding Angle Github app into the orgnaization, **Angle app relaunch doesn't help**

## How to reproduce
1. Install Angle into any Github organization
2. Remove Angle app from the organization
3. Install Angle into the same organization again
4. Open Add new application screen
5. Select a repo from the organization and enter app name
6. Tap on `3. Continuous integration -> button`
7. Observe `Github returned an unathorized response code` alert

## Expected
Application should be created if Angle has access to the repo in the organization

## Screenshots
<img width="640" alt="image" src="https://user-images.githubusercontent.com/4790464/71412019-5a298400-2654-11ea-9b6b-2daaaa05e771.png">

**Comment by pepibumur** [comment]
@Austinate would you mind trying again?

**Comment by Austinate** [comment]
@pepibumur Sure. I’m out on vacation with no laptop so I’ll he able to try only after 14th of January :)

**Comment by pepibumur** [comment]
> @pepibumur Sure. I’m out on vacation with no laptop so I’ll be able to try only after 14th of January :)

Sure! Vacations are vacations :). Enjoy your time off and let's give it a try once you are back on the 14th. I'm looking forward to getting this working and having our first user :)

**Comment by Austinate** [comment]
Latest (49) build of Angle asked me to re-authorize Angle for Mac on GitHub and now I'm able to create apps for personal repos, thanks! 🙏
